from PyQt5.Qt import Qt
from PyQt5.QtWidgets import QFormLayout, QLineEdit, QPushButton, QWidget, QApplication, QListWidget, QVBoxLayout, QLabel, QHBoxLayout, QRadioButton
from data import *

def quesForm():
    question_form.setEnabled(True)
    correct_answer_form.setEnabled(True)
    incorrect_answer_form1.setEnabled(True)
    incorrect_answer_form2.setEnabled(True)
    incorrect_answer_form3.setEnabled(True)
    if radio_btn_quesGui.isChecked():
        width_form.setEnabled(True)
        height_form.setEnabled(True)
    else:
        width_form.setEnabled(False)
        height_form.setEnabled(False)
    

window_e = QWidget()
window_e.resize(1100,500)
window_e.setWindowTitle("Створити питання")
window_e.hide()         
lay = QFormLayout()
layout = QHBoxLayout() 
line1 = QHBoxLayout()
line2 = QHBoxLayout()
layout_m = QVBoxLayout()
listQ = QListWidget()
question_form = QLineEdit()
correct_answer_form = QLineEdit()
incorrect_answer_form1 = QLineEdit()
incorrect_answer_form2 = QLineEdit()
incorrect_answer_form3 = QLineEdit()
width_form = QLineEdit()
height_form = QLineEdit()
question_form.setEnabled(False)
correct_answer_form.setEnabled(False)
incorrect_answer_form1.setEnabled(False)
incorrect_answer_form2.setEnabled(False)
incorrect_answer_form3.setEnabled(False)
width_form.setEnabled(False)
height_form.setEnabled(False)
add_btn = QPushButton("Додати запитання")
remove_btn = QPushButton("Видалити запитання")
startTren_btn = QPushButton("Почати тренування")
question_lbl_a = QLabel("Питання")
correct_answer_lbl = QLabel("Правильна відповідь")
incorrect_answer_lbl1 = QLabel("Неправильна відповідь №1")
incorrect_answer_lbl2 = QLabel("Неправильна відповідь №2")
incorrect_answer_lbl3 = QLabel("Неправильна відповідь №3")
width_lbl = QLabel("Ширина")
height_lbl = QLabel("Висота")
radio_btn_ques = QRadioButton("Question")
radio_btn_quesGui = QRadioButton("Question_gui")
lay.addRow(radio_btn_ques, radio_btn_quesGui)
lay.addRow(question_lbl_a,question_form)
lay.addRow(correct_answer_lbl,correct_answer_form)
lay.addRow(incorrect_answer_lbl1,incorrect_answer_form1)
lay.addRow(incorrect_answer_lbl2,incorrect_answer_form2)
lay.addRow(incorrect_answer_lbl3,incorrect_answer_form3)
lay.addRow(width_lbl, width_form)
lay.addRow(height_lbl, height_form)
layout.addWidget(listQ, stretch =4)
layout.addStretch(0.5)
layout.addLayout(lay, stretch = 5)
layout_m.addLayout(layout)
line1.addWidget(add_btn,stretch = 2)
line1.addStretch(0.5)
line1.addWidget(remove_btn, stretch = 2)
layout_m.addLayout(line1)
line2.addStretch(1)
line2.addWidget(startTren_btn, stretch = 2)
line2.addStretch(1)
layout_m.addLayout(line2)
window_e.setLayout(layout_m)
radio_btn_ques.clicked.connect(quesForm)
radio_btn_quesGui.clicked.connect(quesForm)